"""empty message

Revision ID: 77f929da7ebe
Revises: 
Create Date: 2023-05-30 02:15:14.094738

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '77f929da7ebe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
